fix: add test util to wait for healthy piri (#306)
Aims to fix:

```
=== RUN   TestFXSpaceContentRetrieve/space/content/retrieve
    ucan_fx_test.go:106: 
            Error Trace:    /Users/runner/work/piri/piri/pkg/service/retrieval/ucan_fx_test.go:106
            Error:          Received unexpected error:
                            sending message: doing HTTP request: Get "http://localhost:49232/piece/bafkreibmtmy3p773cf7uj24hfg2dhniov45xv4p54cs4oe3nxhm7p3ov5e": dial tcp [::1]:49232: connect: connection refused
```

Possibly because the server is not ready to accept connections yet.